# Generated by Django 4.1.7 on 2023-06-15 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dns",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("type", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
                ("pri", models.IntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        db_column="company",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dns_company",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company", models.CharField(max_length=255)),
                ("client", models.CharField(max_length=255)),
                ("group", models.CharField(max_length=255)),
                ("domain_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Whois",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_date", models.DateTimeField()),
                ("status", models.CharField(max_length=255)),
                ("registrar", models.CharField(max_length=255)),
                ("expiration_date", models.DateTimeField()),
                ("creation_date", models.DateTimeField()),
                (
                    "client",
                    models.ForeignKey(
                        db_column="client",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whois_client",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        db_column="company",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whois_company",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        db_column="domain",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whois_domain",
                        to="company.domain",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SslLookup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("host", models.CharField(max_length=255)),
                ("issued_to", models.CharField(max_length=255)),
                ("issued_o", models.CharField(blank=True, max_length=255, null=True)),
                ("issuer_c", models.CharField(max_length=255)),
                ("issuer_o", models.CharField(max_length=255)),
                ("issuer_ou", models.CharField(blank=True, max_length=255, null=True)),
                ("issuer_cn", models.CharField(max_length=255)),
                ("cert_sn", models.CharField(max_length=255)),
                ("cert_sha1", models.CharField(max_length=255)),
                ("cert_alg", models.CharField(max_length=255)),
                ("cert_ver", models.IntegerField()),
                ("cert_sans", models.TextField()),
                ("cert_exp", models.BooleanField()),
                ("cert_valid", models.BooleanField()),
                ("valid_from", models.DateField()),
                ("valid_till", models.DateField()),
                ("validity_days", models.IntegerField()),
                ("days_left", models.IntegerField()),
                ("valid_days_to_expire", models.IntegerField()),
                ("tcp_port", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        db_column="company",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ssl_company",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        db_column="domain",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ssl_domain",
                        to="company.domain",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServerInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("server_name", models.CharField(max_length=255)),
                ("server_ip", models.GenericIPAddressField(unpack_ipv4=True)),
                (
                    "server_type",
                    models.CharField(
                        choices=[("WH", "Webhosting"), ("M", "Mail")], max_length=2
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        db_column="company",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="server_company",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("group_name", models.CharField(max_length=255)),
                ("group_type", models.CharField(max_length=255)),
                ("group_color", models.CharField(max_length=255, null=True)),
                ("group_description", models.CharField(max_length=25, null=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        db_column="company",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_company",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Geoip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "dns_type",
                    models.CharField(
                        choices=[("A", "A"), ("NS", "NS"), ("MX", "MX")], max_length=3
                    ),
                ),
                ("status", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("countryCode", models.CharField(max_length=255)),
                ("region", models.CharField(max_length=255)),
                ("regionName", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("zip", models.CharField(max_length=255)),
                ("lat", models.CharField(max_length=255)),
                ("lon", models.CharField(max_length=255)),
                ("timezone", models.CharField(max_length=255)),
                ("isp", models.CharField(max_length=255)),
                ("org", models.CharField(max_length=255)),
                ("asn", models.CharField(max_length=255)),
                ("ip", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        db_column="company",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geoip_company",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dns",
                    models.ForeignKey(
                        db_column="dns",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geoip_dns",
                        to="company.dns",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        db_column="domain",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geoip_domain",
                        to="company.domain",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dns",
            name="domain",
            field=models.ForeignKey(
                db_column="domain",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dns_domain",
                to="company.domain",
            ),
        ),
        migrations.CreateModel(
            name="CmsLookup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cms_id", models.CharField(blank=True, max_length=100, null=True)),
                ("cms_name", models.CharField(blank=True, max_length=100, null=True)),
                ("cms_url", models.URLField(blank=True, null=True)),
                ("cms_version", models.IntegerField(blank=True, null=True)),
                (
                    "detection_param",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_scanned", models.DateTimeField(blank=True, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                ("wp_license", models.URLField(blank=True, null=True)),
                ("wp_plugins", models.TextField(blank=True, null=True)),
                ("wp_readme_file", models.URLField(blank=True, null=True)),
                (
                    "wp_theme_version",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("wp_themes", models.CharField(blank=True, max_length=100, null=True)),
                ("wp_users", models.TextField(blank=True, null=True)),
                ("wp_version", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        db_column="company",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cms_company",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        db_column="domain",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cms_domain",
                        to="company.domain",
                    ),
                ),
            ],
        ),
    ]
